### ISSUE TITLE
bug: Test version is slow only on MacOS

### ISSUE THREAD

**Issue by matthewfeickert** [pyhf/pyhf-validation#14]
In the CI 

https://github.com/pyhf/pyhf-validation/blob/a75fe22a139c494ad63e8625fb6871813b9ec3a8/tests/test_cli.py#L6-L16

will often fail as it will take longer than 1 second for `test_version` to complete but _only_ on MacOS. I am not sure _why_ it is only MacOS, but this should be resolved.

c.f. PR #9

**Comment by kratsg** [comment]
Just saw this.. sorry. MacOS has a longer PYTHONPATH included by default, and I think you might see some extra slowdown b/c of that... I'd check the pythonpath, and other env variable settings to see where the slowdown is (executable lookup or actual code execution?)
